#!/usr/bin/env python3

from urllib.request import urlopen
import os
import datetime
import platform


OUTPUT_FILENAME = 'root_certificates_generated.hpp'
MAX_AGE_DAYS = 1

def creation_date(filename):
  """
  Try to get the date that a file was created, falling back to when it was
  last modified if that isn't possible.
  See http://stackoverflow.com/a/39501288/1709587 for explanation.
  """
  if platform.system() == 'Windows':
    return os.path.getctime(filename)
  stat = os.stat(filename)
  try:
    return stat.st_birthtime
  except AttributeError:
    return stat.st_mtime

def missing_or_outdated(filename):
  if not os.path.exists(filename):
    return True
  return creation_date(filename) < (datetime.datetime.now() - datetime.timedelta(days=MAX_AGE_DAYS)).timestamp()

def main():
  if (missing_or_outdated(OUTPUT_FILENAME)):
    print('Creating ' + OUTPUT_FILENAME + ' ...')
    with urlopen('https://curl.haxx.se/ca/cacert.pem') as input:
      with open(OUTPUT_FILENAME, 'w+') as output:
        output.write('// this file was generated by pwned-server/loadtest/cert/getcerts.py\n')
        output.write('#ifndef __ROOT_CERT_INCLUDE_HPP__\n')
        output.write('#define __ROOT_CERT_INCLUDE_HPP__\n')
        output.write('#define ROOT_CERTIFICATES (\\\n')
        incert = False
        for l in input:
          line = l.decode('utf-8').strip()
          if incert:
            output.write('"' + line + '\\n" \\\n')
            if line.startswith('-----END CERTIFICATE-----'):
              incert = False
          elif line.startswith('-----BEGIN CERTIFICATE-----'):
            incert = True
            output.write('"' + line + '\\n" \\\n')
        output.write('"\\n")\n')
        output.write('#endif // __ROOT_CERT_INCLUDE_HPP__\n')

if __name__ == '__main__':
  main()
