openapi: 3.0.0
info:
  title: pwned lookup API
  description: REST API to query an MD5:count file for a hash
  version: '1.0'
  contact:
    name: pwned support
    email: ola@ct.de
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.txt

servers:
  - url: https://example.com:{port}/v1/pwned/api
    description: main server
    variables:
      port:
        enum:
          - '31337'
          - '443'
          - '80'
        default: '443'

paths:
  /lookup:
    get:
      parameters:
        - in: query
          name: hash
          required: true
          schema:
            type: string
            pattern: /[0-9a-fA-F]{32}/
          description: The hex encoded MD5 hash to look up
      summary: Query an MD5 hash and return the numbers of times it was found
      responses:
        '200':
          description: A JSON object containing the hash and the number of times it was found
          content:
            application/json:
              schema:
                type: object
                properties:
                  hash:
                    type: string
                  found:
                    type: integer
                    description: Number of times the hash has been found
                  lookup-time-ms:
                    type: number
                    description: Lookup time in milliseconds
  /info:
    get:
      responses:
        '200':
          description: A JSON object containing infos about the server
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    description: Number of different hashes in database
                  last-update:
                    type: number
                    description: Date when the database was last updated, i.e. number of seconds (not counting leap seconds) since 00:00, Jan 1 1970 UTC, corresponding to POSIX time.
