language: cpp
script:
  - cd build/Release
  - cmake -DCMAKE_BUILD_TYPE=Release ../..
  - make
compiler:
  - clang
  - g++
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang
    - cmake-data
    - cmake
sudo: false
