name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake-configure
      uses: snickerbockers/cmake-configure@prerel1
    - name: cmake
      run: |
        cd build/Release |
        cmake -DCMAKE_BUILD_TYPE=Release ../..
    - name: make
      run: make
